tap "d12frosted/emacs-plus"

brew "fzf"
brew "mise"
brew "starship"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "betterdisplay"
cask "emacs-plus-app"
cask "font-blex-mono-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "ghostty"
cask "hammerspoon"
cask "stats"
cask "visual-studio-code"
cask "zed"
